## numpy - Numerical Python

In [1]:
import numpy as np

In [18]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

print(arr[3] + arr[1])

print(arr[0:3]) #slicing the first three numbers in the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
6
[1 2 3]


In [3]:
x = [1,2,3,4,5]
type(x)

list

In [4]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
y = (1,2,3,4,5)
type(y)

tuple

In [28]:
#2-D array

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)



[[1 2 3]
 [4 5 6]]
2


In [30]:
print(arr.shape)

(2, 3)


In [26]:
#3-D array

arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [27]:
print(arr.shape)

(1, 3, 3)


In [11]:
x = np.array(7)
print(x.ndim)

0


In [19]:
a = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(a)

[[1 2 3 4 5]
 [4 5 6 7 8]]


In [20]:
# index to access 5

a[1,1]

# Row index 1, column index 1

5

In [21]:
# slice elements 6,7,8

a[1, 2:]

array([6, 7, 8])

In [22]:
# copying the array

x = np.array([11,22,33,44])

y = x.copy()

print(x)
print(y)

[11 22 33 44]
[11 22 33 44]


In [24]:
# copying the array

x = np.array([11,22,33,44])

y = x.copy()

x[0] = 1

print(x)
print(y)

[ 1 22 33 44]
[11 22 33 44]


In [23]:
# to create a view for an array

x = np.array([11,22,33,44])

v = x.view()

print(x)
print(v)

[11 22 33 44]
[11 22 33 44]


In [25]:
# to create a view for an array

x = np.array([11,22,33,44])

v = x.view()
x[0] = 1


print(x)
print(v)

[ 1 22 33 44]
[ 1 22 33 44]


In [31]:
a = np.array([1,2,3,4,5,5,6,6,7,8])

print(a.shape)

(10,)


In [32]:
print(a.reshape(5,2))

[[1 2]
 [3 4]
 [5 5]
 [6 6]
 [7 8]]


In [33]:
print(a.reshape(3,3))

ValueError: cannot reshape array of size 10 into shape (3,3)

In [34]:
a = np.array([1,2,3,4,5,5,6,6])

print(a.shape)

#how can I reshape the 1D array to 2D array?

(8,)


In [37]:
a = np.array([1,2,3,4,5,5,6,6])
b = np.array([1,2,3,4,5,5,6,6])

add = np.concatenate((a,b))

add

array([1, 2, 3, 4, 5, 5, 6, 6, 1, 2, 3, 4, 5, 5, 6, 6])

In [38]:
a = np.array([1,2,3])
b = np.array([1,2,3,4,5,5,6,6])

add = np.concatenate((a,b))

add

array([1, 2, 3, 1, 2, 3, 4, 5, 5, 6, 6])

In [40]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

arr = np.concatenate((a,b))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

arr = np.stack((a,b), axis=1)

arr

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [42]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

arr = np.stack((a,b), axis=0)

arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])