## Numpy - continuation

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6])

# splitting numpy arrays

x = np.array_split(arr,3)

x

[array([1, 2]), array([3, 4]), array([5, 6])]

In [6]:
arr = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])

# splitting numpy arrays

x = np.array_split(arr,2)

x

[array([[1, 2, 3, 4, 5, 6]]), array([[1, 2, 3, 4, 5, 6]])]

In [7]:
# searching in the array for a certain value

arr = np.array([1,2,3,4,5,6])

x = np.where(arr == 3) # returns the index of that particular value
x

(array([2], dtype=int64),)

In [8]:
# searching in the array for a certain value

arr = np.array([1,2,3,4,5,6,4,3,3,4,5,5,5,5])

x = np.where(arr == 5) # returns the index of that particular value
x

(array([ 4, 10, 11, 12, 13], dtype=int64),)

In [9]:
# searching in the array for a certain value

arr = np.array([1,2,3,4,5,6,4,3,3,4,5,5,5,5])

x = np.where(arr%2 == 0) # returns the index of that particular value
x

(array([1, 3, 5, 6, 9], dtype=int64),)

In [12]:
# sorting arrays

arr = np.array([12,44,22,1])

print(np.sort(arr))

[ 1 12 22 44]


In [13]:
arr = np.array([[12,44,22,1],[2,80,11,36]])

print(np.sort(arr))

[[ 1 12 22 44]
 [ 2 11 36 80]]


In [14]:
# filtering the values in the array

arr = np.array([12,44,22,1,85,36])

filt = arr > 40

print(arr)

x = arr[filt]

print(x)


[12 44 22  1 85 36]
[44 85]


## Random module

In [15]:
from numpy import random

In [21]:
x = random.randint(100)
print(x)

94


In [23]:
x = random.randint(10,15)
print(x)

14


In [25]:
x = random.rand()
print(x)

0.8449802385178711


In [26]:
x = random.randint(10, size=(4))
print(x)

[2 0 3 9]


In [28]:
x = random.randint(40, size=(3,2))
print(x)

[[ 6  1]
 [32 32]
 [24 33]]


## Pandas

In [29]:
import pandas as pd

In [31]:
dt = {
    'course': ["Python", "AI/ML", "Testing"],
    'TotalHrs': [25,30,30]
}

print(dt)
print(type(dt))

{'course': ['Python', 'AI/ML', 'Testing'], 'TotalHrs': [25, 30, 30]}
<class 'dict'>


In [32]:
df = pd.DataFrame(dt)

print(df)

    course  TotalHrs
0   Python        25
1    AI/ML        30
2  Testing        30


In [33]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [34]:
# series is more like a column in the table

x = [1,2,3]

ser = pd.Series(x)

print(ser)
print(type(ser))

0    1
1    2
2    3
dtype: int64
<class 'pandas.core.series.Series'>


In [35]:
# series is more like a column in the table

x = [1,2,3]

ser = pd.Series(x, index=['a','b','c'])


print(ser)
print(type(ser))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [36]:
print(ser['b'])

2


In [38]:
# locating a row in a dataframe

dt = {
    'course': ["Python", "AI/ML", "Testing"],
    'TotalHrs': [25,30,30]
}

df = pd.DataFrame(dt)

print(df)
print(type(df))

    course  TotalHrs
0   Python        25
1    AI/ML        30
2  Testing        30
<class 'pandas.core.frame.DataFrame'>


In [40]:
print(df.loc[1])

course      AI/ML
TotalHrs       30
Name: 1, dtype: object


In [42]:
print(df.loc[0:1])

   course  TotalHrs
0  Python        25
1   AI/ML        30


In [43]:
df = pd.DataFrame(dt, index = ['course_1','course_2','course_3'])

print(df)

           course  TotalHrs
course_1   Python        25
course_2    AI/ML        30
course_3  Testing        30


In [44]:
print(df.loc['course_2'])

course      AI/ML
TotalHrs       30
Name: course_2, dtype: object


## Pandas using dataset

In [45]:
from sklearn.datasets import load_iris

In [46]:
iris = load_iris()

iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [48]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [51]:
df['species'] = iris.target

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [52]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [53]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
145        2  
146        2  
147        2  
148        2  
149        2

In [54]:
df.tail(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
140                6.7               3.1                5.6               2.4   
141                6.9               3.1                5.1               2.3   
142                5.8               2.7                5.1               1.9   
143                6.8               3.2                5.9               2.3   
144                6.7               3.3                5.7               2.5   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
140        2  
141        2  
142        2  
143        2  
144        2  
145        2  
146        2  
147        2  
148        2  
149        2

In [55]:
df.shape

(150, 5)

In [57]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species'],
      dtype='object')

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [59]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)     species  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [60]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

In [61]:
df.isnull().count()

sepal length (cm)    150
sepal width (cm)     150
petal length (cm)    150
petal width (cm)     150
species              150
dtype: int64

In [62]:
df['species'].unique()

# find out the number of entries in each category?

array([0, 1, 2])

In [63]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species'],
      dtype='object')

In [64]:
df['sepal length (cm)']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64

In [65]:
df[['sepal length (cm)', 'sepal width (cm)']]

sepal length (cm)  sepal width (cm)
0                  5.1               3.5
1                  4.9               3.0
2                  4.7               3.2
3                  4.6               3.1
4                  5.0               3.6
..                 ...               ...
145                6.7               3.0
146                6.3               2.5
147                6.5               3.0
148                6.2               3.4
149                5.9               3.0

[150 rows x 2 columns]

In [66]:
# selecting using the label

df.loc[0:5]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  
5        0

In [67]:
# selecting by the position/ index

df.iloc[0:5]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [68]:
# filtering any of the columns by a condition

df[df['sepal length (cm)']>5.0]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
10                 5.4               3.7                1.5               0.2   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
5          0  
10         0  
14         0  
15         0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[118 rows x 5 columns]

In [69]:
# mapping the labels (0,1,2) to category names

df['speciesName'] = df['species'].map({
    0:'setosa',
    1:'versicolor',
    2:'virginica'
})

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species speciesName  
0          0      setosa  
1          0      setosa  
2          0      setosa  
3          0      setosa  
4          0      setosa  
..       ...         ...  
145        2   virginica  
146        2   virginica  
147        2   virginica  
148        2   virginica  
149        2   virginica  

[150 rows x 6 columns]